---
- name: 0.系统初始化   ## 执行操作的任务名称
  gather_facts: false
  hosts:  ## 所执行操作任务的节点
    - test
  roles:  ## roles文件夹下面所对应的文件夹下面
    - e7-base 
  tags: e7-base

- name: 1.自签证书
  gather_facts: false
  hosts: localhost
  roles:
    - tls
  tags: tls

- name: 2.部署Docker
  gather_facts: false
  hosts: k8s
  roles:
    - docker
  tags: docker
