---
- name: 0.系统初始化
  gather_facts: false
  hosts:
    - vmware
  roles:
    - initialization
  tags: initialization

- name: 1.自签证书
  gather_facts: false
  hosts: localhost
  roles:
    - tls
  tags: tls

- name: 2.部署Docker
  gather_facts: false
  hosts: k8s
  roles:
    - docker
  tags: docker
